# Generated by Django 2.2.6 on 2019-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_uuid',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
