# Generated by Django 2.2.6 on 2019-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20191026_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_uuid',
            field=models.CharField(max_length=100),
        ),
    ]
