version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata fixtures.json && python manage.py runserver 0.0.0.0:8000"
    container_name: democracy
    volumes:
      - .:/democracy
    environment:
          - DATABASE_URL=://root:password@mysql/locationz
          - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],*
    ports:
      - "8004:8004"